[package]
name = "ferveo"
version = "0.1.0"
authors = ["Metastate AG <hello@metastate.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bls12_381 = "0.3.1"
ff = "0.8.0"
rand = "0.7.3"
